[2025-09-20T12:02:36.781+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: manual_full_load.load_dim_store manual__2025-09-20T10:02:30.721682+00:00 [queued]>
[2025-09-20T12:02:36.789+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: manual_full_load.load_dim_store manual__2025-09-20T10:02:30.721682+00:00 [queued]>
[2025-09-20T12:02:36.793+0200] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-09-20T12:02:36.805+0200] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): load_dim_store> on 2025-09-20 10:02:30.721682+00:00
[2025-09-20T12:02:36.808+0200] {standard_task_runner.py:57} INFO - Started process 7189 to run task
[2025-09-20T12:02:36.812+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'manual_full_load', 'load_dim_store', 'manual__2025-09-20T10:02:30.721682+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/manual_full_load.py', '--cfg-path', '/tmp/tmpnfn8_5yf']
[2025-09-20T12:02:36.817+0200] {standard_task_runner.py:85} INFO - Job 93: Subtask load_dim_store
[2025-09-20T12:02:36.886+0200] {task_command.py:410} INFO - Running <TaskInstance: manual_full_load.load_dim_store manual__2025-09-20T10:02:30.721682+00:00 [running]> on host 1102361e702e
[2025-09-20T12:02:36.978+0200] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='manual_full_load' AIRFLOW_CTX_TASK_ID='load_dim_store' AIRFLOW_CTX_EXECUTION_DATE='2025-09-20T10:02:30.721682+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-20T10:02:30.721682+00:00'
[2025-09-20T12:02:36.978+0200] {sql.py:265} INFO - Executing: 
        INSERT INTO dwh.dim_store (store_id, store_name, region)
        SELECT DISTINCT store_id, 'Unknown', 'Unknown'
        FROM staging.sales_stg
        ON CONFLICT (store_id) DO NOTHING;
        
[2025-09-20T12:02:37.002+0200] {base.py:73} INFO - Using connection ID 'postgres_retail' for task execution.
[2025-09-20T12:02:37.080+0200] {base.py:73} INFO - Using connection ID 'postgres_retail' for task execution.
[2025-09-20T12:02:37.086+0200] {sql.py:375} INFO - Running statement: 
        INSERT INTO dwh.dim_store (store_id, store_name, region)
        SELECT DISTINCT store_id, 'Unknown', 'Unknown'
        FROM staging.sales_stg
        ON CONFLICT (store_id) DO NOTHING;
        , parameters: None
[2025-09-20T12:02:37.089+0200] {sql.py:384} INFO - Rows affected: 0
[2025-09-20T12:02:37.114+0200] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=manual_full_load, task_id=load_dim_store, execution_date=20250920T100230, start_date=20250920T100236, end_date=20250920T100237
[2025-09-20T12:02:37.155+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-09-20T12:02:37.208+0200] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
